// <auto-generated />
using System;
using AccessRequestHub.API.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccessRequestHub.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccessRequestHub.API.Models.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<string>("ClientRequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequesterEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ClientRequestId")
                        .IsUnique();

                    b.HasIndex("RequesterEmail");

                    b.ToTable("access_requests");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemOwnerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SystemOwnerEmail");

                    b.ToTable("applications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CRM",
                            SystemOwnerEmail = "carol@example.local"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finance Portal",
                            SystemOwnerEmail = "dana@example.local"
                        });
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActorEmail");

                    b.HasIndex("RequestId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.User", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ManagerEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Email");

                    b.HasIndex("ManagerEmail");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Email = "alice@example.local",
                            ManagerEmail = "bob@example.local",
                            Name = "Alice",
                            Role = "Requester"
                        },
                        new
                        {
                            Email = "bob@example.local",
                            Name = "Bob",
                            Role = "Manager"
                        },
                        new
                        {
                            Email = "carol@example.local",
                            Name = "Carol",
                            Role = "SystemOwner"
                        },
                        new
                        {
                            Email = "dana@example.local",
                            Name = "Dana",
                            Role = "SystemOwner"
                        },
                        new
                        {
                            Email = "erin@example.local",
                            Name = "Erin",
                            Role = "Auditor"
                        });
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.AccessRequest", b =>
                {
                    b.HasOne("AccessRequestHub.API.Models.Application", "Application")
                        .WithMany("AccessRequests")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessRequestHub.API.Models.User", "Requester")
                        .WithMany("AccessRequests")
                        .HasForeignKey("RequesterEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.Application", b =>
                {
                    b.HasOne("AccessRequestHub.API.Models.User", "SystemOwner")
                        .WithMany("OwnedApplications")
                        .HasForeignKey("SystemOwnerEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SystemOwner");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.AuditLog", b =>
                {
                    b.HasOne("AccessRequestHub.API.Models.User", "Actor")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorEmail")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccessRequestHub.API.Models.AccessRequest", "AccessRequest")
                        .WithMany("AuditLogs")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccessRequest");

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.User", b =>
                {
                    b.HasOne("AccessRequestHub.API.Models.User", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerEmail");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.AccessRequest", b =>
                {
                    b.Navigation("AuditLogs");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.Application", b =>
                {
                    b.Navigation("AccessRequests");
                });

            modelBuilder.Entity("AccessRequestHub.API.Models.User", b =>
                {
                    b.Navigation("AccessRequests");

                    b.Navigation("AuditLogs");

                    b.Navigation("DirectReports");

                    b.Navigation("OwnedApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
